spring.application.name=APPLICATION-GATEWAY

server.port=7575
spring.cloud.gateway.enabled=true
# Gateway Routing
spring.cloud.gateway.routes[0].id=CUSTOMER-SERVICE
spring.cloud.gateway.routes[0].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/customers/**

spring.cloud.gateway.routes[1].id=ACCOUNT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/accounts/**


spring.cloud.gateway.routes[2].id=CartService
spring.cloud.gateway.routes[2].uri=lb://CartService
spring.cloud.gateway.routes[2].predicates[0]=Path=/cart/**

spring.cloud.gateway.routes[3].id=InventoryService
spring.cloud.gateway.routes[3].uri=lb://InventoryService
spring.cloud.gateway.routes[3].predicates[0]=Path=/inventory/**

spring.cloud.gateway.routes[4].id=NotificationService
spring.cloud.gateway.routes[4].uri=lb://NotificationService
spring.cloud.gateway.routes[4].predicates[0]=Path=/notification/**

spring.cloud.gateway.routes[5].id=OrderService
spring.cloud.gateway.routes[5].uri=lb://OrderService
spring.cloud.gateway.routes[5].predicates[0]=Path=/order/**

spring.cloud.gateway.routes[6].id=PaymentService
spring.cloud.gateway.routes[6].uri=lb://PaymentService
spring.cloud.gateway.routes[6].predicates[0]=Path=/payments/**

spring.cloud.gateway.routes[7].id=ProductService
spring.cloud.gateway.routes[7].uri=lb://ProductService
spring.cloud.gateway.routes[7].predicates[0]=Path=/products/**



spring.cloud.gateway.routes[8].id=IdentityService
spring.cloud.gateway.routes[8].uri=lb://IdentityService
spring.cloud.gateway.routes[8].predicates[0]=Path=/auth/**


spring.cloud.gateway.routes[9].id=ProductDetailService
spring.cloud.gateway.routes[9].uri=lb://ProductDetailService
spring.cloud.gateway.routes[9].predicates[0]=Path=/product-details/**


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*